---
openapi: 3.0.0
info:
  title: Replay API
  description: This is a simple API
  contact:
    email: akshatjoshi@microsoft.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/AKSHATJOSHI1234_1/replay/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /replay/status/{id}:
    get:
      tags:
      - developers
      summary: get status of replay operation
      description: |
        By passing replayId , you can get the replay operation status
      parameters:
      - name: id
        in: path
        description: pass the replay id.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria and returns details of replay operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReplayStatus'
              examples:
                Status:
                  $ref: '#/components/examples/Status'
                StatusFailed:
                  $ref:  '#/components/examples/StatusFailed'
                StatusFailedForKind:
                  $ref:  '#/components/examples/StatusFailedForKind'
                StatusPassedForKind:
                  $ref:  '#/components/examples/StatusPassedForKind'
        "404":
          description: replay id not found
  /replay:
    post:
      tags:
      - admins
      summary: replay based on type
      description: replay all the kinds
      requestBody:
        description: replay based on type
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplayRequest'
            examples:
               KindAll:
                  $ref: '#/components/examples/KindAll'
               Kinds:
                  $ref: '#/components/examples/Kinds'
      responses:
        "202":
          description: A response object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        "400":
          description: "invalid input, object invalid"
components:
  schemas:
    ReplayRequest:
      type: object
      required:
      - operation
      properties:
        operation:
          type: string
        filter:
          anyOf:
          - $ref: '#/components/schemas/Kind'
    ReplayStatus:
      required:
      - replayId
      - operation
      - totalRecords
      - processedRecords
      - state
      - totalTime
      - status
      type: object
      properties:
        kind:
          type: string
        replayId:
          type: string
        totalRecords:
          type: integer
          format: int64
        processedRecords:
          type: integer
          format: int64
        state:
          type: string
        startedAt:
          type: string
          format: date
        elapsedTime:
          type: string
          format: duration
        filter:
          type: array
          items:
            type: object
        status:
          type: array
          items:
            type: object
          properties:
                  kind:
                     type: string 
                  totalRecords:
                    type: integer
                    format: int64
                  processedRecords:
                    type: integer
                    format: int64
                  state:
                    type: string
                  startedAt:
                    type: string
                    format: date
                  elapsedTime:
                    type: string
                    format: duration
                  avgProcessingTimePerMinute:
                    type: integer
                    format: int64
    Status:
      required:
      - replayId
      type: object
      properties:
        replayId:
          type: integer
          example: 1000
    Kind:
      type: array
      items:
        type: string
        example: "osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0"
  examples:
     KindAll:
        value:
           operation: reindex
     Kinds:
        value:
           operation: reindex
           filter: {"kinds":["osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0"]} 
     Status:
         value:
            replayId: "1000"
            operation: "reindex"
            totalRecordsOverall: 2
            processedRecordsOverall: 1
            startedAt: 2023-07-21T17:32:28Z 
            elapsedTime: 23 
            OverallState: IN_PROGRESS 
            filter: {}
            status: 
              [
              {
              kind: "*",
              totalRecords: 2,
              processedRecords: 1,
              state: "IN_PROGRESS",
              startedAt: "2023-07-21T17:32:28Z",
              elapsedTime: "23",
              avgProcessingTimePerMinute: "1",
              }
              ]
     StatusFailed:
          value:
            replayId: "1000"
            operation: "reindex"
            totalRecords: 2
            processedRecords: 1
            startedAt: 2023-07-21T17:32:28Z
            elapsedTime: 23
            state: "FAILED"
            filter: {}
            status: 
              [
              {
              kind: "*",
              totalRecords: 2,
              processedRecords: 1,
              state: "FAILED",
              startedAt: "2023-07-21T17:32:28Z",
              elapsedTime: "23",
              avgProcessingTimePerMinute: "1",
              }
              ]
                
     StatusFailedForKind:
          value:
            replayId: "1000"
            operation: "reindex" 
            totalRecords: 2
            processedRecords: 1
            startedAt: 2023-07-21T17:32:28Z
            elapsedTime: 23
            state: "FAILED"
            filter: {"kinds":["osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0"]}
            status: 
              [
              {
              kind: "osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0",
              totalRecords: 2,
              processedRecords: 1,
              state: "FAILED",
              startedAt: "2023-07-21T17:32:28Z",
              elapsedTime: "23",
              avgProcessingTimePerMinute: "1",
              }
              ]
     StatusPassedForKind:
         value:
            replayId: "1000"
            operation: "reindex"
            totalRecordsOverall: 2
            processedRecordsOverall: 1
            startedAt: 2023-07-21T17:32:28Z
            elapsedTime: 23
            OverallState: IN_PROGRESS
            filter: {"kinds":["osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0"]}
            status: 
              [
              {
              kind: "osdu:wks:reference-data--VelocityAnalysisMethod:1.0.0",
              totalRecords: 2,
              processedRecords: 1,
              state: "IN_PROGRESS",
              startedAt: "2023-07-21T17:32:28Z",
              elapsedTime: "23",
              avgProcessingTimePerMinute: "1",
              }
              ]
